version: "3.7"
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
services:
  server:
    container_name: server
    build:
      context: ./httpd
    ports:
      - 8090:80
    networks:
      - frontend
      - backend
  php:
    container_name: php
    build:
      context: ./php
    working_dir: /srv/strona
    networks:
      - backend
  mysql:
    container_name: baza_danych
    build:
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=haslo123
    volumes:
      - ./baza_danych:/var/lib/mysql
    networks:
      - backend
